export const bookTypes = {
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_BOOK: 'SET_BOOK',
    ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
    ADD_BOOK_FAIL: 'ADD_BOOK_FAIL',
    UPDATE_BOOK_SUCCESS: 'UPDATE_BOOK_SUCCESS',
    UPDATE_BOOK_FAIL: 'UPDATE_BOOK_FAIL',
    RESET_BOOK: 'RESET_BOOK'
}

export const userTypes = {
    SET_USER: 'SET_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    RESET_USER: 'RESET_USER',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE:'SET_TOTAL_PAGE'
}